import Layout from "@/components/Layout";
import { CartProvider } from "@/contexts/cart";
import "@/styles/globals.css";

export const metadata = {
  title: "Fashion",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Layout>{children}</Layout>
        </CartProvider>
      </body>
    </html>
  );
}
